analytic/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from analytic import views, admin
from analytic.views import  TableDataView
from django.conf.urls import url

from djgeojson.views import GeoJSONLayerView

from .models import Event
from . import views




urlpatterns = [
    url(r'^$', views.map, name='map'),
    url(r'^teables/$', TableDataView.as_view(), name='tables'),
    url(r'^leaflet/$', views.leaflet, name='leaflet'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^events/$', views.data, name='data'),
    url(r'^unverified_events/$', views.unverified_data, name='unverified_data'),
    url(r'^report/$', views.new_event, name='report'),
    url(r'^post-event/$', views.update_event, name='post-event'),
    # url(r'^appdata/$', views.appdata, name='appdata'),
    # url(r'^help/$', views.help, name='help'),
    url(r'^data.geojson/$',
        GeoJSONLayerView.as_view(model=Event, properties=('report', 'name', 'date_verified', 'category',)),
        name='events_data'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.category_detail, name='event_category'),
    url(r'^event/(?P<id>[0-9A-Fa-f-]+)/$', views.event_detail, name='event_detail'),
]

analytics/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('analytic.urls', namespace='analytic')),
    url(r'^twitter/', include('twitter.urls', namespace='twitter')),
    url(r'^auth/', include('authentication.urls')),
    url(r'^auth/api/', include('authentication.api.urls'), name='account-api'),
    url(r'^events/api/', include('analytic.api.urls'), name='event-api'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^post-tweet/$', views.post_tweet, name='post-tweet'),
    url(r'^twitter-settings/$', views.twitter_settings, name='twitter-settings'),
    url(r'^search/$', views.GenerateKeyWordView.as_view(), name='search-form'),
    url(r'^twitter/$', views.twitter, name='twitter'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>K-Analytics</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-dashboard.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
{#            {% include 'sidebar.html' %}#}
        {% block content %}{% endblock %}
    </div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src="{% static 'js/plugins/chartjs.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/now-ui-dashboard.js' %}"></script>
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'demo/demo.js' %}"></script>


</html>

templates/footer.html
 <footer class="footer">
                <div class="container-fluid">
                    <nav>
                        <ul>

                        </ul>
                    </nav>
                    <div class="copyright">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>, Designed by
                        <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
                        <a href="#" target="_blank">Karungu</a>.
                    </div>
                </div>
            </footer>

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}




{% block content %}
<div class="main-panel">
            <!-- Navbar -->
           {% include 'navbar.html' %}
            <!-- End Navbar -->
            <div class="panel-header panel-header-sm">
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card ">
                            <div class="card-header ">
                                Map
                            </div>
                            <div class="card-body ">
                                <div id="map" class="map"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           {% include 'footer.html' %}
        </div>
{% endblock %}

templates/navbar.html
 <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary fixed-top">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#pablo">Maps</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <form>
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                                </span>
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="now-ui-icons media-2_sound-wave"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Stats</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="now-ui-icons location_world"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Twitter</span>
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'twitter:twitter-settings' %}">Twitter Settings</a>
                                    <a class="dropdown-item" href="{% url 'twitter:search-form' %}">Twitter Search</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="now-ui-icons users_single-02"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Account</span>
                                    </p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

templates/search_results.html
{#{% extends 'base/master.html' %}#}

{% block content %}
<div class="main-panel">
<nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Analytics Dashboard </a>
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <p>You searched for: <strong>{{ query }}</strong></p>
                        <div class="col-lg-9 col-md-9 col-sm-9">
                            <div class="card">
                                <div class="card-content">
                                    {% if texts %}
            <p>Found {{ texts|length }} Tweet{{ texts|pluralize }}.</p>
            <ul>
                {% for text in texts %}
                <li><b>{{ text.tweet_id }}</b>| {{ text.text }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tweets matched your search criteria.</p>
        {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </div>
{% endblock %}
<p>You searched for: <strong>{{ query }}</strong></p>

        {% if texts %}
            <p>Found {{ texts|length }} Tweet{{ texts|pluralize }}.</p>
            <ul>
                {% for text in texts %}
                <li>{{ text.tweet_id }}| {{ text.text }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No tweets matched your search criteria.</p>
        {% endif %}

templates/sidebar.html
<div class="sidebar" data-color="orange">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text logo-mini">
                    K
                </a>
                <a href="http://www.creative-tim.com" class="simple-text logo-normal">
                    Analytics
                </a>
            </div>
<div class="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <form>
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Search...">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                                </span>
                            </div>
                        </form>
                    </li>
                 {% with url_name=request.resolver_match.url_name %}
                    <li class="{% if url_name == 'index' %}active{% endif %}">
                        <a href="{% url 'analytic:map' %}">
                            <i class="now-ui-icons location_map-big"></i>
                            <p>Maps</p>
                        </a>
                    </li>

                    <li class="{% if url_name == 'tables' %}active{% endif %}">
                        <a href="{% url 'analytic:tables' %}">
                            <i class="now-ui-icons design_bullet-list-67"></i>
                            <p>Data List</p>
                        </a>
                    </li>
                          <li class="{% if url_name == 'twitter' %}active{% endif %}">
                        <a href="{% url 'twitter:twitter' %}">
                            <i class="now-ui-icons design_bullet-list-67"></i>
                            <p>Twitter</p>
                        </a>
                    </li>

                     <li>
                        <a href="../examples/user.html">
                            <i class="now-ui-icons business_chart-bar-32"></i>
                            <p>Analytics</p>
                        </a>
                    </li>

                     <li>
                        <a href="../examples/user.html">
                            <i class="now-ui-icons users_single-02"></i>
                            <p>User Profile</p>
                        </a>
                    </li>
                {% endwith %}

                </ul>
            </div>

</div>

templates/tables.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
    <div class="main-panel">
            <!-- Navbar -->
           {% include 'navbar.html' %}
            <!-- End Navbar -->

        <div class="panel-header panel-header-sm">
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title"> Simple Table</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class=" text-primary">
                                            <th>
                                                Name
                                            </th>
                                            <th>
                                                Country
                                            </th>
                                            <th>
                                                City
                                            </th>
                                            <th class="text-right">
                                                Salary
                                            </th>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    Dakota Rice
                                                </td>
                                                <td>
                                                    Niger
                                                </td>
                                                <td>
                                                    Oud-Turnhout
                                                </td>
                                                <td class="text-right">
                                                    $36,738
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Minerva Hooper
                                                </td>
                                                <td>
                                                    Curaçao
                                                </td>
                                                <td>
                                                    Sinaai-Waas
                                                </td>
                                                <td class="text-right">
                                                    $23,789
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Sage Rodriguez
                                                </td>
                                                <td>
                                                    Netherlands
                                                </td>
                                                <td>
                                                    Baileux
                                                </td>
                                                <td class="text-right">
                                                    $56,142
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Philip Chaney
                                                </td>
                                                <td>
                                                    Korea, South
                                                </td>
                                                <td>
                                                    Overland Park
                                                </td>
                                                <td class="text-right">
                                                    $38,735
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Doris Greene
                                                </td>
                                                <td>
                                                    Malawi
                                                </td>
                                                <td>
                                                    Feldkirchen in Kärnten
                                                </td>
                                                <td class="text-right">
                                                    $63,542
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Mason Porter
                                                </td>
                                                <td>
                                                    Chile
                                                </td>
                                                <td>
                                                    Gloucester
                                                </td>
                                                <td class="text-right">
                                                    $78,615
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Jon Porter
                                                </td>
                                                <td>
                                                    Portugal
                                                </td>
                                                <td>
                                                    Gloucester
                                                </td>
                                                <td class="text-right">
                                                    $98,615
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>



    {% include 'footer.html' %}
        </div>


{% endblock %}