analytics/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('analytic.urls', namespace='analytic')),
    url(r'^twitter/', include('twitter.urls', namespace='twitter')),
    url(r'^auth/', include('authentication.urls')),
    url(r'^auth/api/', include('authentication.api.urls'), name='account-api'),
    url(r'^events/api/', include('analytic.api.urls'), name='event-api'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^post-tweet/$', views.post_tweet, name='post-tweet'),
    url(r'^twitter-settings/$', views.twitter_settings, name='twitter-settings'),
    url(r'^search/$', views.GenerateKeyWordView.as_view(), name='search-form'),
    url(r'^twitter/$', views.twitter, name='twitter'),
]

analytic/models.py
import uuid
from django.db import models
from django.contrib.gis.db import models
from django.utils import timezone
# Create your models here.
from django.urls import reverse

STATUS_CHOICES = (
    ('verified', 'Verified'),
    ('unverified', 'Unverified'),)

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    class Meta:
        ordering = 'name',
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('event_category',
                       args=[self.slug])

class EventManager(models.Manager):
    def get_queryset(self):
        #exclude out events with null name fields
        return super(EventManager, self).get_queryset().filter(status='verified', name__gt='', name__isnull=False)


class UnverifiedEventManager(models.Manager):
    def get_queryset(self):
        #fetch events with null name fields
        return super(UnverifiedEventManager, self).get_queryset().filter(status='unverified')

class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # agent = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    slug = models.SlugField(max_length=200, null=True, blank=True)
    date_reported = models.DateTimeField(auto_now_add=True)
    report = models.TextField()
    event_image = models.ImageField(upload_to='event_images', null=True, blank=True)
    category = models.ForeignKey(Category, related_name='events' ,on_delete=models.CASCADE, null=True, blank=True)
    address = models.TextField(max_length=200, null=True, blank=True)
    geom = models.PointField(null=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='unverified')
    objects = models.GeoManager()
    verified = EventManager()
    unverified = UnverifiedEventManager()

    def __str__(self):
        return self.report

    def get_absolute_url(self):
        return reverse('event_detail',
                       args=[self.id])

templates/events/dashboard.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="page-title">
                    <h3>Dashboard</h3>
        {% block breadcrumbs %}
                    <div class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="active"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        </ol>
                    </div>
            {% endblock %}
                </div>
    <div id="main-wrapper">
                    <div class="row">
                        <div class="col-lg-3 col-md-6">
                            <div class="panel info-box panel-white">
                                <div class="panel-body">
                                    <div class="info-box-stats">
                                        <p class="counter">{{ events_count }}</p>
                                        <span class="info-box-title">Reported events</span>
                                    </div>
                                    <div class="info-box-icon">
                                        <i class=" icon-list"></i>
                                    </div>
                                    <div class="info-box-progress">
                                        <div class="progress progress-xs progress-squared bs-n">
                                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="panel info-box panel-white">
                                <div class="panel-body">
                                    <div class="info-box-stats">
                                        <p class="counter">{{ tweet_count }}</p>
                                        <span class="info-box-title">Tweets collected</span>
                                    </div>
                                    <div class="info-box-icon">
                                        <i class="icon-social-twitter"></i>
                                    </div>
                                    <div class="info-box-progress">
                                        <div class="progress progress-xs progress-squared bs-n">
                                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="panel info-box panel-white">
                                <div class="panel-body">
                                    <div class="info-box-stats">
                                        <p><span class="counter">{{ text_count }}</span></p>
                                        <span class="info-box-title">SMS recieved</span>
                                    </div>
                                    <div class="info-box-icon">
                                        <i class="icon-envelope"></i>
                                    </div>
                                    <div class="info-box-progress">
                                        <div class="progress progress-xs progress-squared bs-n">
                                            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <div class="panel info-box panel-white">
                                <div class="panel-body">
                                    <div class="info-box-stats">
                                        <p class="counter">{{ user_count }}</p>
                                        <span class="info-box-title">Agents available</span>
                                    </div>
                                    <div class="info-box-icon">
                                        <i class="icon-users"></i>
                                    </div>
                                    <div class="info-box-progress">
                                        <div class="progress progress-xs progress-squared bs-n">
                                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Row -->
                    <div class="row">
                        <div class="col-lg-9 col-md-9">
                            <div class="panel panel-white">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Recently Verified Reports</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive project-stats">
                                       <table class="table">
                                           <thead>
                                               <tr>
                                                   <th>Title</th>
                                                   <th>Date</th>
                                                   <th>Status</th>
                                               </tr>
                                           </thead>
                                           <tbody>
                                           {% for event in events %}
                                               <tr>
                                                   <td><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></td>
                                                    <td><strong>{{ event.date_reported }}</strong></td>
                                                   <td><span class="label label-info">{{ event.status }}</span></td>
                                               </tr>
                                           {% endfor %}
                                           </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- Main Wrapper -->

{% endblock %}


                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                    <marquee id="ticker">
                        {% for tweet in latest_tweets %}
                        {{ tweet.text }} ||
                        {% endfor %}
                    </marquee>
                </div>

templates/events/data.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="page-title">
                    <h3>Verified Events</h3>
        {% block breadcrumbs %}
                    <div class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                            <li class="active">Verified events</li>
                        </ol>
                    </div>
            {% endblock %}
                </div>

    <div id="main-wrapper">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Real-time Feed</h4>
                                </div>
                                <div  id="task_status_div" class="panel-body">
                                    <div class="table-responsive project-stats">
                                       <table id="task_status"  class="table">
                                           <thead>
                                               <tr>
                                                   <th>Report</th>
                                                   <th>Date</th>

                                               </tr>
                                           </thead>
                                           <tbody>

                                           </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Verified Reports</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive project-stats">
                                       <table class="table">
                                           <thead>
                                               <tr>
                                                   <th>Name</th>
                                                   <th>Category</th>
                                                   <th>Date</th>
                                               </tr>
                                           </thead>
                                           <tbody>
                                           {% for t in event %}
                                               <tr>
                                                   <td><a href="{{ t.get_absolute_url }}">{{ t.name }}</a></td>
                                                    <td><strong>{{ t.category }}</strong></td>
                                                    <td>{{ t.date_reported }}</td>
                                               </tr>
                                           {% endfor %}
                                           </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- Row -->
    <script>
        $(function() {

            var ws_path = new WebSocket('ws://' + window.location.host + '/events/');
            console.log("Connecting to " + ws_path);

            ws_path.onopen = function open() {
                console.log('WebSockets connection created.');
            };

            ws_path.onmessage = function(message) {
                console.log("Got message: "+ message.data);
                var data =JSON.parse(message.data);
                var task_status = $("#task_status");
                var ele = $('<tr></tr>');
{#                ele.attr("id", data[0].fields.name);#}
{#                var item_name = $("<td></td>").text(data[0].fields.agent);#}
{#                ele.append(item_name);#}
                var item_report = $("<td></td>").text(data[0].fields.report);
                ele.append(item_report);
                var item_date = $("<td></td>").text(data[0].fields.date_reported);
                ele.append(item_date);
                task_status.append(ele);

                var modal_status = $("#bsModal3");
                var modal_name = $('#mySmallModalLabel').text(data[0].fields.name);
                var modal_report = $('#mySmallModalContent').text(data[0].fields.report);
                modal_status.modal('show');

                setTimeout(function(){
                    $('#bsModal3').modal('hide')
                }, 3000);

            };
        });
    </script>
         <div class="col-md-4">
             <div class="modal fade bs-example-modal-sm" id="bsModal3" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                 <div class="modal-dialog modal-sm">
                     <div class="modal-content">
                         <div class="modal-header">
                             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                             <h4 class="modal-title" id="mySmallModalLabel"></h4>
                         </div>
                         <div id="mySmallModalContent" class="modal-body">
                         </div>
                         <div class="modal-footer">
                             <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
                </div>

{% endblock %}

templates/events/event_category.html
{#{% extends 'base/master.html' %}#}
{% block content %}
<div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"> Category Events</a>
                    </div>
{#                    <div class="collapse navbar-collapse">#}
{#                        <ul class="nav navbar-nav navbar-right">#}
{#                            <li>#}
{#                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">#}
{#                                    <i class="material-icons">dashboard</i>#}
{#                                    <p class="hidden-lg hidden-md">Dashboard</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="dropdown">#}
{#                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">#}
{#                                    <i class="material-icons">notifications</i>#}
{#                                    <span class="notification">5</span>#}
{#                                    <p class="hidden-lg hidden-md">Notifications</p>#}
{#                                </a>#}
{#                                <ul class="dropdown-menu">#}
{#                                    <li>#}
{#                                        <a href="#">Mike John responded to your email</a>#}
{#                                    </li>#}
{#                                    <li>#}
{#                                        <a href="#">You have 5 new tasks</a>#}
{#                                    </li>#}
{#                                    <li>#}
{#                                        <a href="#">You're now friend with Andrew</a>#}
{#                                    </li>#}
{#                                    <li>#}
{#                                        <a href="#">Another Notification</a>#}
{#                                    </li>#}
{#                                    <li>#}
{#                                        <a href="#">Another One</a>#}
{#                                    </li>#}
{#                                </ul>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">#}
{#                                    <i class="material-icons">person</i>#}
{#                                    <p class="hidden-lg hidden-md">Profile</p>#}
{#                                </a>#}
{#                            </li>#}
{#                        </ul>#}
{#                        <form class="navbar-form navbar-right" role="search">#}
{#                            <div class="form-group  is-empty">#}
{#                                <input type="text" class="form-control" placeholder="Search">#}
{#                                <span class="material-input"></span>#}
{#                            </div>#}
{#                            <button type="submit" class="btn btn-white btn-round btn-just-icon">#}
{#                                <i class="material-icons">search</i>#}
{#                                <div class="ripple-container"></div>#}
{#                            </button>#}
{#                        </form>#}
{#                    </div>#}
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Events</h4>
                                </div>
                                <div class="card-content table-responsive">
                                    <table class="table">
                                        <thead class="text-primary">
                                            <th> Name </th>
                                            <th> Agent Contact</th>
                                            <th> Date Report</th>
                                        </thead>
                                        <tbody>
                                        {% for event in event_category %}
                                            <tr class="odd gradeX">
                                              <td>{{ event.name }}</td>
                                              <td>{{ event.agent }}</td>
                                              <td>{{ event.date_reported }}</td>
                                            </tr>
                                          {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/events/event_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
 <div id="main-wrapper">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="panel panel-white">
                                <div class="panel-heading">
                                    <h4 class="panel-title"> Event report</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="panel-body">
                                        <div class="timeline-item-header">
                                                    <p><strong>{{ event.name }}</strong></p>
                                                    <small>{{ event.date_reported }}</small>
                                                </div>
                                                <div class="timeline-item-post">
                                                    <p>{{ event.report }}</p>
                                                </div>
                        </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="panel panel-white">
                                <div class="panel-heading">
                                    <h4 class="panel-title"> Event Image</h4>
                                </div>
                                <div class="panel-body imgx">
                                    <img src="{% if event.event_image %}{{ event.event_image.url }}{% else %}{% static 'assets/images/no-image.png' %}{% endif %}" alt="Event image" height="220" width="220">
                                </div>
                            </div>
                        </div>
                    </div><!-- Row -->
                </div>

{% endblock %}

templates/events/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/events/report.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% load leaflet_tags %}

{% block content %}
    <style>
    #id_geom-map {
    width: 90%;
}
    </style>
<div class="page-title">
                    <h3>Report Event</h3>
        {% block breadcrumbs %}
                    <div class="page-breadcrumb">
                        <ol class="breadcrumb">
{#                            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>#}
                            <li class="active">Report Event</li>
                        </ol>
                    </div>
            {% endblock %}
                </div>

<div id="main-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-white">
                        <div class="panel-heading clearfix">
                                    <h4 class="panel-title">Report Event</h4>
                                </div>
                        <div id="task_status_div" class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form action="{{ action }}" method="post" class="form-horizontal" enctype="multipart/form-data">
                                        <div class="col-md-10">
                                        {% leaflet_js plugins="forms" %}
                                                {% leaflet_css plugins="forms" %}

                                                {% csrf_token %}
                                                {% crispy event_form %}
                                        </div>

                                    </form>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
</div>

{% endblock %}

templates/events/unverified_data.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
    <div class="page-title">
                    <h3>Unverified Events</h3>
        {% block breadcrumbs %}
                    <div class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                            <li class="active">Unverified events</li>
                        </ol>
                    </div>
            {% endblock %}
                </div>
    <div id="main-wrapper">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="panel panel-white">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Verified Reports</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive project-stats">
                                       <table class="table">
                                           <thead>
                                               <tr>
                                                   <th>Name</th>
                                                   <th>Category</th>
                                                   <th>Date</th>
                                                   <th>Action</th>
                                               </tr>
                                           </thead>
                                           <tbody>
                                           {% for t in event %}
                                               <tr>
                                                   <td>{{ t.report }}</td>
                                                    <td><strong>{{ t.category }}</strong></td>
                                                    <td>{{ t.date_reported }}</td>
                                               <td><button id="btnEvent" type="button" class="btn btn-primary btn-xs btnEvent" data-smsid="{{t.id}}" onclick="window.open('/post-event/?event_id={{t.id}}', '_self');"> Post Event</button></td>
                                               </tr>
                                           {% endfor %}
                                           </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% if event.has_other_pages %}
                            <ul class="pagination">
                                {% if event.has_previous %}
                                    <li><a href="?page={{ event.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                                {% else %}
                                    <li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
                                {% endif %}
                                {% if event.number|add:'-4' > 1 %}
                                    <li><a href="?page={{ event.number|add:'-5' }}">&hellip;</a></li>
                                {% endif %}
                                {% for i in event.paginator.page_range %}
                                    {% if event.number == i %}
                                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% elif i > event.number|add:'-5' and i < event.number|add:'5' %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if event.paginator.num_pages > event.number|add:'4' %}
                                    <li><a href="?page={{ event.number|add:'5' }}">&hellip;</a></li>
                                {% endif %}
                                {% if event.has_next %}
                                    <li><a href="?page={{ event.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                                {% else %}
                                    <li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
                                {% endif %}
                            </ul>
                                    {% endif %}
                    </div><!-- Row -->
                </div>
{% endblock %}